// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0eWPimRlxPFIreUC9mLqKa9mch7qDq9Y',
    appId: '1:318775180903:web:06081417bb13668f5c1ec2',
    messagingSenderId: '318775180903',
    projectId: 'loginpage-fc8d2',
    authDomain: 'loginpage-fc8d2.firebaseapp.com',
    storageBucket: 'loginpage-fc8d2.firebasestorage.app',
    measurementId: 'G-5ER9W5Z7WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSzhOrt0q3BlKNMAV7Nd3jIbvLWshMgY',
    appId: '1:318775180903:android:156b28446827d9fb5c1ec2',
    messagingSenderId: '318775180903',
    projectId: 'loginpage-fc8d2',
    storageBucket: 'loginpage-fc8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRaZ49-bNaWtnG6yE3HP131nx6EIxwGo',
    appId: '1:318775180903:ios:29c4bcf18071ef8f5c1ec2',
    messagingSenderId: '318775180903',
    projectId: 'loginpage-fc8d2',
    storageBucket: 'loginpage-fc8d2.firebasestorage.app',
    iosBundleId: 'com.example.equipManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRaZ49-bNaWtnG6yE3HP131nx6EIxwGo',
    appId: '1:318775180903:ios:29c4bcf18071ef8f5c1ec2',
    messagingSenderId: '318775180903',
    projectId: 'loginpage-fc8d2',
    storageBucket: 'loginpage-fc8d2.firebasestorage.app',
    iosBundleId: 'com.example.equipManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2oy6Tx3Sni2zElehSoptw6AoOT_9tRH4',
    appId: '1:318775180903:web:b54c95505237de825c1ec2',
    messagingSenderId: '318775180903',
    projectId: 'loginpage-fc8d2',
    authDomain: 'loginpage-fc8d2.firebaseapp.com',
    storageBucket: 'loginpage-fc8d2.firebasestorage.app',
    measurementId: 'G-GGYJ807M74',
  );
}
