// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxc60RTDKUrFXySLqq1cQ9He6zOC0QFdQ',
    appId: '1:402034937114:web:1cb7604eedb46cf55170a3',
    messagingSenderId: '402034937114',
    projectId: 'equipmanager-69ade',
    authDomain: 'equipmanager-69ade.firebaseapp.com',
    storageBucket: 'equipmanager-69ade.firebasestorage.app',
    measurementId: 'G-QHNJ62Y8C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrD02af0E9RgCZC7aLnpmEGlEA-WxmYq8',
    appId: '1:402034937114:android:c5a2236405f0865f5170a3',
    messagingSenderId: '402034937114',
    projectId: 'equipmanager-69ade',
    storageBucket: 'equipmanager-69ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0yDonZZIVSjPq_YGjE20Qx-HuXop14zM',
    appId: '1:402034937114:ios:aa25a392bf61d3c55170a3',
    messagingSenderId: '402034937114',
    projectId: 'equipmanager-69ade',
    storageBucket: 'equipmanager-69ade.firebasestorage.app',
    iosBundleId: 'com.example.equipManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0yDonZZIVSjPq_YGjE20Qx-HuXop14zM',
    appId: '1:402034937114:ios:aa25a392bf61d3c55170a3',
    messagingSenderId: '402034937114',
    projectId: 'equipmanager-69ade',
    storageBucket: 'equipmanager-69ade.firebasestorage.app',
    iosBundleId: 'com.example.equipManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxc60RTDKUrFXySLqq1cQ9He6zOC0QFdQ',
    appId: '1:402034937114:web:3750b4041c7b6ce85170a3',
    messagingSenderId: '402034937114',
    projectId: 'equipmanager-69ade',
    authDomain: 'equipmanager-69ade.firebaseapp.com',
    storageBucket: 'equipmanager-69ade.firebasestorage.app',
    measurementId: 'G-G1WMPVZENM',
  );
}
